import { strict as assert } from 'node:assert';
import { createServer } from '../tools/serve.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/Users/macbookpro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
try{
  const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/assets/stamba/landmark.js*',r=>r.abort());await page.goto(origin);
  await page.locator('[data-error="stamba"]').waitFor({state:'visible'});
  await page.getByRole('button',{name:'Visit My workspace',exact:true}).tap();await page.waitForFunction(()=>worldDiagnostics().place==='room'&&!worldDiagnostics().moving);
  assert.equal(await page.evaluate(()=>worldDiagnostics().loaded),3);
  await page.unroute('**/assets/stamba/landmark.js*');await page.locator('[data-error="stamba"] button').click();await page.waitForFunction(()=>worldDiagnostics().loaded===4);
  assert.equal(await page.locator('#load-errors').isVisible(),false);
  await page.getByRole('button',{name:'Visit Stamba',exact:true}).tap();await page.waitForFunction(()=>worldDiagnostics().moving);
  assert.equal(await page.evaluate(()=>worldDiagnostics().visiblePlaces),4,'travel must reveal its destination before arrival');
  await page.waitForFunction(()=>!worldDiagnostics().moving);assert.equal(await page.evaluate(()=>worldDiagnostics().visiblePlaces),1);
  await page.getByRole('button',{name:'Visit Bocconi library',exact:true}).tap();await page.getByRole('button',{name:'Study room',exact:true}).click();
  await page.getByRole('button',{name:'Close entrance doors',exact:true}).click();await page.getByRole('button',{name:'Back to world',exact:true}).click();
  await page.getByRole('button',{name:'Visit Bocconi library',exact:true}).click();await page.getByRole('button',{name:'Study room',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Open entrance doors',exact:true}).count(),1);
  await page.getByRole('button',{name:'Music for this place',exact:false}).click();await page.getByRole('button',{name:'Load official player',exact:true}).click();assert.equal(await page.locator('iframe').count(),1);
  await page.context().setOffline(true);await page.waitForFunction(()=>document.querySelectorAll('iframe').length===0);
  await page.context().setOffline(false);assert.equal(await page.locator('iframe').count(),0);
  await page.getByRole('button',{name:'Back to world',exact:true}).click();await page.waitForFunction(()=>!worldDiagnostics().moving);
  const idle=await page.evaluate(()=>worldDiagnostics().frames);await page.waitForTimeout(400);assert.ok(await page.evaluate(()=>worldDiagnostics().frames)<=idle+1,'idle scene should not continuously render');
  await page.getByRole('button',{name:'Visit QSI Tbilisi',exact:true}).click();await page.waitForFunction(()=>!worldDiagnostics().moving);await page.goBack();await page.waitForFunction(()=>worldDiagnostics().place===null);
  await page.evaluate(()=>document.querySelector('canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));
  await page.getByRole('button',{name:'Visit My workspace',exact:true}).click();
  assert.equal(await page.locator('#loading-status').getAttribute('data-complete'),'true','fallback navigation must not restart a disposed renderer loader');
  const early=await browser.newPage({viewport:{width:390,height:844}});let release;
  const held=new Promise(r=>{release=r;});await early.route('**/assets/room/landmark.js',async route=>{await held;await route.continue();});
  await early.goto(origin+'/#room');await early.locator('#room-light').waitFor({state:'visible'});
  assert.equal(await early.getByRole('button',{name:'Lamplight',exact:true}).isEnabled(),false,'lighting waits for its source anchor');
  assert.equal(await early.getByRole('button',{name:'The shelves',exact:true}).isEnabled(),false,'presets wait for their model');
  release();await early.waitForFunction(()=>worldDiagnostics().loaded===4&&!worldDiagnostics().moving);
  assert.equal(await early.getByRole('button',{name:'Lamplight',exact:true}).isEnabled(),true);
  await early.getByRole('button',{name:'The shelves',exact:true}).click();await early.waitForFunction(()=>!worldDiagnostics().moving);
  await early.screenshot({path:new URL('../.impeccable/review/mobile-shelves.png',import.meta.url).pathname,fullPage:true});await early.close();
  assert.deepEqual(errors,[]);console.log('Factory failure/retry, touch visits, travel visibility, preserved door state, browser offline music cleanup, no reconnect autoplay, idle rendering and history: passed.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
